# Generated by Django 2.2 on 2020-09-07 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20200907_1412'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-created'], 'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
    ]
